[versions]
kotlin = "2.1.20"
coroutines = "1.6.0-native-mt"
kermit = "1.0.0"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
